[2024-09-07T23:58:05.673+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-07T23:57:59.633009+00:00 [queued]>
[2024-09-07T23:58:05.681+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-07T23:57:59.633009+00:00 [queued]>
[2024-09-07T23:58:05.681+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-07T23:58:05.681+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-07T23:58:05.681+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-07T23:58:05.693+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-07 23:57:59.633009+00:00
[2024-09-07T23:58:05.698+0000] {standard_task_runner.py:55} INFO - Started process 1671 to run task
[2024-09-07T23:58:05.701+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-07T23:57:59.633009+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpyvjdu8ol']
[2024-09-07T23:58:05.702+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask train_model
[2024-09-07T23:58:05.752+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-07T23:57:59.633009+00:00 [running]> on host 394f8fce6b56
[2024-09-07T23:58:05.933+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-07T23:57:59.633009+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-07T23:57:59.633009+00:00
[2024-09-07T23:58:05.934+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-07T23:58:05.940+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240907T235759, start_date=20240907T235805, end_date=20240907T235805
[2024-09-07T23:58:05.950+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task train_model (No module named 'sklearn'; 1671)
[2024-09-07T23:58:05.993+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-07T23:58:06.012+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
