[2024-09-08T01:52:18.660+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [queued]>
[2024-09-08T01:52:18.666+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [queued]>
[2024-09-08T01:52:18.667+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:52:18.667+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T01:52:18.667+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:52:18.678+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-08 01:52:12.733498+00:00
[2024-09-08T01:52:18.682+0000] {standard_task_runner.py:55} INFO - Started process 228 to run task
[2024-09-08T01:52:18.684+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-08T01:52:12.733498+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpzp0xr79n']
[2024-09-08T01:52:18.685+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask train_model
[2024-09-08T01:52:18.727+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [running]> on host 2bb1ac50cbe0
[2024-09-08T01:52:18.881+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-08T01:52:12.733498+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-08T01:52:12.733498+00:00
[2024-09-08T01:52:18.881+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T01:52:18.886+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240908T015212, start_date=20240908T015218, end_date=20240908T015218
[2024-09-08T01:52:18.897+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 88 for task train_model (No module named 'sklearn'; 228)
[2024-09-08T01:52:18.937+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T01:52:18.957+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
