[2024-09-08T02:00:33.539+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [queued]>
[2024-09-08T02:00:33.546+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [queued]>
[2024-09-08T02:00:33.546+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T02:00:33.546+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-09-08T02:00:33.546+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T02:00:33.558+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-08 01:52:12.733498+00:00
[2024-09-08T02:00:33.561+0000] {standard_task_runner.py:55} INFO - Started process 98 to run task
[2024-09-08T02:00:33.564+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-08T01:52:12.733498+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp5i0fji1u']
[2024-09-08T02:00:33.565+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask train_model
[2024-09-08T02:00:33.608+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:52:12.733498+00:00 [running]> on host 6556fb296dfa
[2024-09-08T02:00:33.653+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-08T01:52:12.733498+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-08T01:52:12.733498+00:00
[2024-09-08T02:00:34.005+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 26, in train_model
    df = pd.read_csv('/tmp/preprocessed_train.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/preprocessed_train.csv'
[2024-09-08T02:00:34.012+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=train_model, execution_date=20240908T015212, start_date=20240908T020033, end_date=20240908T020034
[2024-09-08T02:00:34.022+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task train_model ([Errno 2] No such file or directory: '/tmp/preprocessed_train.csv'; 98)
[2024-09-08T02:00:34.057+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T02:00:34.075+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
