[2024-09-08T00:00:07.260+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:00:07.267+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:00:07.267+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T00:00:07.267+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T00:00:07.267+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T00:00:07.278+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-07 00:00:00+00:00
[2024-09-08T00:00:07.282+0000] {standard_task_runner.py:55} INFO - Started process 1969 to run task
[2024-09-08T00:00:07.285+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpa_hctzre']
[2024-09-08T00:00:07.286+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask train_model
[2024-09-08T00:00:07.330+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [running]> on host 394f8fce6b56
[2024-09-08T00:00:07.496+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-07T00:00:00+00:00
[2024-09-08T00:00:07.497+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T00:00:07.501+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240907T000000, start_date=20240908T000007, end_date=20240908T000007
[2024-09-08T00:00:07.510+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task train_model (No module named 'sklearn'; 1969)
[2024-09-08T00:00:07.537+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T00:00:07.559+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T00:12:35.676+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:12:35.683+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T00:12:35.683+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T00:12:35.683+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T00:12:35.683+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T00:12:35.695+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-07 00:00:00+00:00
[2024-09-08T00:12:35.699+0000] {standard_task_runner.py:55} INFO - Started process 861 to run task
[2024-09-08T00:12:35.702+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpgs8axml5']
[2024-09-08T00:12:35.703+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask train_model
[2024-09-08T00:12:35.747+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [running]> on host 8c084782485a
[2024-09-08T00:12:35.915+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-07T00:00:00+00:00
[2024-09-08T00:12:35.916+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T00:12:35.921+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240907T000000, start_date=20240908T001235, end_date=20240908T001235
[2024-09-08T00:12:35.930+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task train_model (No module named 'sklearn'; 861)
[2024-09-08T00:12:35.954+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T00:12:35.971+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T01:41:55.079+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T01:41:55.086+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T01:41:55.087+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:41:55.087+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T01:41:55.087+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:41:55.099+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-07 00:00:00+00:00
[2024-09-08T01:41:55.103+0000] {standard_task_runner.py:55} INFO - Started process 302 to run task
[2024-09-08T01:41:55.106+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpves6dynu']
[2024-09-08T01:41:55.107+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask train_model
[2024-09-08T01:41:55.146+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [running]> on host 9bbae47dc133
[2024-09-08T01:41:55.313+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-07T00:00:00+00:00
[2024-09-08T01:41:55.313+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T01:41:55.318+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240907T000000, start_date=20240908T014155, end_date=20240908T014155
[2024-09-08T01:41:55.328+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 71 for task train_model (No module named 'sklearn'; 302)
[2024-09-08T01:41:55.358+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T01:41:55.376+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T02:01:57.293+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T02:01:57.310+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-08T02:01:57.310+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T02:01:57.310+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T02:01:57.310+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T02:01:57.387+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-07 00:00:00+00:00
[2024-09-08T02:01:57.398+0000] {standard_task_runner.py:55} INFO - Started process 330 to run task
[2024-09-08T02:01:57.416+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpm7bp9dl4']
[2024-09-08T02:01:57.421+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask train_model
[2024-09-08T02:01:57.665+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model scheduled__2024-09-07T00:00:00+00:00 [running]> on host 6556fb296dfa
[2024-09-08T02:01:57.921+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-07T00:00:00+00:00
[2024-09-08T02:01:59.372+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-09-08T02:01:59.384+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=train_model, execution_date=20240907T000000, start_date=20240908T020157, end_date=20240908T020159
[2024-09-08T02:01:59.439+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-08T02:01:59.454+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
