[2024-09-08T01:41:53.870+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [queued]>
[2024-09-08T01:41:53.879+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [queued]>
[2024-09-08T01:41:53.879+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:41:53.879+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-08T01:41:53.879+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:41:53.892+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-08 01:41:47.187231+00:00
[2024-09-08T01:41:53.897+0000] {standard_task_runner.py:55} INFO - Started process 299 to run task
[2024-09-08T01:41:53.900+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-08T01:41:47.187231+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp6tu3wcu_']
[2024-09-08T01:41:53.902+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask train_model
[2024-09-08T01:41:53.950+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [running]> on host 9bbae47dc133
[2024-09-08T01:41:54.140+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-08T01:41:47.187231+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-08T01:41:47.187231+00:00
[2024-09-08T01:41:54.141+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T01:41:54.147+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=train_model, execution_date=20240908T014147, start_date=20240908T014153, end_date=20240908T014154
[2024-09-08T01:41:54.158+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task train_model (No module named 'sklearn'; 299)
[2024-09-08T01:41:54.193+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T01:41:54.213+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
