[2024-09-08T01:46:55.388+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [queued]>
[2024-09-08T01:46:55.394+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [queued]>
[2024-09-08T01:46:55.394+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:46:55.394+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-09-08T01:46:55.394+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-08T01:46:55.406+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-08 01:41:47.187231+00:00
[2024-09-08T01:46:55.410+0000] {standard_task_runner.py:55} INFO - Started process 321 to run task
[2024-09-08T01:46:55.412+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-08T01:41:47.187231+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpvj_lycsj']
[2024-09-08T01:46:55.413+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask train_model
[2024-09-08T01:46:55.463+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-08T01:41:47.187231+00:00 [running]> on host 0ef1cf3b829d
[2024-09-08T01:46:55.642+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-09-08T01:41:47.187231+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-08T01:41:47.187231+00:00
[2024-09-08T01:46:55.642+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 23, in train_model
    from sklearn.ensemble import RandomForestRegressor
ModuleNotFoundError: No module named 'sklearn'
[2024-09-08T01:46:55.647+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=train_model, execution_date=20240908T014147, start_date=20240908T014655, end_date=20240908T014655
[2024-09-08T01:46:55.656+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task train_model (No module named 'sklearn'; 321)
[2024-09-08T01:46:55.664+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-08T01:46:55.685+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
